baseURL = "https://donodoo.it/"
languageCode = "it"
title = "Donodoo API Documentation"
theme = "docuapi"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = true
pygmentsOptions = ""
pygmentsStyle = "monokai"

# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

defaultContentLanguage = "it"

[params]
search = true
  
# Configure the language example tabs.
[[params.language_tabs]]
key = "python"
name = "Python"

[[params.language_tabs]]
key = "php"
name = "PHP" 




