baseURL = "https://donodoo.it/"
languageCode = "en-us"
title = "Donodoo API Documentation"
theme = "docuapi"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true

defaultContentLanguage = "en"


[params]
search = true
  
# Configure the language example tabs.
[[params.language_tabs]]
key = "python"
name = "Python" 
[[params.language_tabs]]
key = "php"
name = "PHP" 



